services:
  minitwitter.api:
    image: ${DOCKER_REGISTRY-}minitwitterapi
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: MiniTwitter.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=MiniTwitterDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=true
    
    depends_on:
      - db
    networks:
      - mini-twitter-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1400:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - mini-twitter-net

networks:
  mini-twitter-net:
    driver: bridge

volumes:
  sqlvolume: