services:
  minitwitter.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      # Cloudinary credentials (use env vars, not hardcoded)
      - CLOUDINARYSETTINGS__CLOUDNAME=${CLOUDINARYSETTINGS__CLOUDNAME}
      - CLOUDINARYSETTINGS__APIKEY=${CLOUDINARYSETTINGS__APIKEY}
      - CLOUDINARYSETTINGS__APISECRET=${CLOUDINARYSETTINGS__APISECRET}
      - SENDGRID__APIKEY=${SENDGRID__APIKEY}
      - SENDGRID__FROM_EMAIL=${SENDGRID__FROM_EMAIL}
      - SENDGRID__FROM_NAME=${SENDGRID__FROM_NAME}
      
    ports:
      - "8180:8080"
      - "8181:8081"
    volumes:
      # Secret/Https volumes (keep as is)
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

      #Mount local source code to /app inside container
      - .:/app

    working_dir: /app/MiniTwitter.API

    #Use dotnet watch for hot reloading
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]
