services:
  minitwitter.api:
    image: ${DOCKER_REGISTRY-}minitwitterapi
    ports:
      - "8180:8080"
      - "8181:8081"
     #  - "8082:8082"
    build:
      context: .
      dockerfile: MiniTwitter.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MiniTwitterDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=true
    
    depends_on:
      - db
    networks:
      - mini-twitter-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1533:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - mini-twitter-net


  migrate:
    build:
      context: .
      dockerfile: MiniTwitter.API/Dockerfile
      target: migrate-env    # <- important: use migrate-env target stage from Dockerfile
    working_dir: /src/MiniTwitter.API
    command:
      [
        "dotnet", "ef", "database", "update",
        "--project", "../MiniTwitter.Data/MiniTwitter.Data.csproj",
        "--startup-project", "."
      ]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MiniTwitterDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=true
    depends_on:
      - db
    networks:
      - mini-twitter-net

networks:
  mini-twitter-net:
    driver: bridge

volumes:
  sqlvolume: